export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const MESSAGES_SET_NEW_COUNTS = "MESSAGES_SET_NEW_COUNTS";
export const MESSAGES_REMOVE_NEW_COUNTS = "MESSAGES_REMOVE_NEW_COUNTS";

export const CURRENT_USER_SET_INFO = "CURRENT_USER_SET_INFO";
export const CURRENT_USER_REMOVE = "CURRENT_USER_REMOVE";

export const HOME_SELECT_GROUP = "HOME_SELECT_GROUP";

export const GROUPS_SET_GROUPS = "GROUPS_SET_GROUPS";
