export const ACCESS_TOKEN_SET_INFO_SUCCEEDED = 'ACCESS_TOKEN_SET_INFO_SUCCEEDED';
export const ACCESS_TOKEN_CLEAR_ALL = 'ACCESS_TOKEN_CLEAR_ALL';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
export const UI_HOME_ACTIVE_DRAWER = 'UI_HOME_ACTIVE_DRAWER';
export const UI_HOME_INACTIVE_DRAWER = 'UI_HOME_INACTIVE_DRAWER';

export const MESSAGES_SET_NEW_COUNTS = 'MESSAGES_SET_NEW_COUNTS';
export const MESSAGES_REMOVE_NEW_COUNTS = 'MESSAGES_REMOVE_NEW_COUNTS';

export const CURRENT_USER_LOAD_INFO_RESPONDED = 'CURRENT_USER_LOAD_INFO_RESPONDED';

export const HOME_LOAD_GROUPS_RESPONDED = 'HOME_LOAD_GROUPS_RESPONDED';
export const HOME_START_LOADING = 'HOME_START_LOADING';
export const HOME_STOP_LOADING = 'HOME_STOP_LOADING';

export const CHANNELS_LOAD_POSTS_RESPONDED = 'CHANNELS_LOAD_POSTS_RESPONDED';
export const CHANNELS_LOAD_POSTS_SUCCEEDED = 'CHANNELS_LOAD_POSTS_SUCCEEDED';
export const CHANNELS_START_LOADING = 'CHANNELS_START_LOADING';
export const CHANNELS_STOP_LOADING = 'CHANNELS_STOP_LOADING';
export const CHANNELS_CLEAR_ALL = 'CHANNELS_CLEAR_ALL';

export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
