export const ACCESS_TOKEN_SET_INFO_SUCCEEDED = "ACCESS_TOKEN_SET_INFO_SUCCEEDED";
export const ACCESS_TOKEN_CLEAR_ALL_SUCCEEDED = "ACCESS_TOKEN_CLEAR_ALL_SUCCEEDED";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const MESSAGES_SET_NEW_COUNTS = "MESSAGES_SET_NEW_COUNTS";
export const MESSAGES_REMOVE_NEW_COUNTS = "MESSAGES_REMOVE_NEW_COUNTS";

export const CURRENT_USER_LOAD_INFO_RESPONDED = "CURRENT_USER_LOAD_INFO_RESPONDED";
export const CURRENT_USER_CLEAR_ALL = "CURRENT_USER_CLEAR_ALL";

export const HOME_SELECT_GROUP = "HOME_SELECT_GROUP";
export const HOME_SELECT_CHANNEL = "HOME_SELECT_CHANNEL";
export const HOME_LOAD_GROUPS_RESPONDED = "HOME_LOAD_GROUPS_RESPONDED";

export const CHANNELS_LOAD_POSTS_RESPONDED = "CHANNELS_LOAD_POSTS_RESPONDED";
export const CHANNELS_LOAD_POSTS_SUCCEEDED = "CHANNELS_LOAD_POSTS_SUCCEEDED";
export const CHANNELS_LOAD_POSTS_FAILED = "CHANNELS_LOAD_POSTS_FAILED";
export const CHANNELS_RESET_ERROR = "CHANNELS_RESET_ERROR";
